## Basic Configuration
theme = "noteworthy"
baseurl = "https://nakabonne.dev"
languageCode = "en-us"
author = "Ryo Nakao"
title = "Ryo Nakao"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

[taxonomies]
  tag = "tags"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
  unsafe = true

## Site Settings
[params]
	math = true
	description = "a random walk through topics that interest me"
  # For social links
  github = "https://github.com/nakabonne"
	linkedin = "https://www.linkedin.com/in/nakabonne"
  twitter = "https://twitter.com/nakabonne"
  # For Twitter card and OGP
  title = "Ryo Nakao"
  images = ["/img/icon.png"] # Used as an image appeared when shared on SNS.

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2

